export const products = [
  {
    id: 1,
    img: "https://foodal.com/wp-content/uploads/2014/09/must-have-kitchen-gadets.jpg",
    name: "Kitchen Products",
    discription: "kitchen item and all kitchen equipements",
      
  },
  {
    id: 2,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVT0E2GojskstD2kPhXu5yg1aNO4UKlnHC6Q&usqp=CAU",
    name: "Clothing",
    discription: "all type of garment and clothings",
  },
  {
    id: 3,
    img: "https://thumbs.dreamstime.com/b/many-used-modern-electronic-gadgets-use-white-floor-reuse-recycle-concept-top-view-153892483.jpg",
    name: "Electroinics items",
    discription: "All type of electronics mobile phone etc",
  },
  {
    id: 4,
    img: "https://3.imimg.com/data3/KQ/DM/MY-10863971/footwear-500x500.png",
    name: "Footware",
    discription: "All type of footware and boots",
  },
  {
    id: 5,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtgcSRamq_SDT356YjSRdo7eqf7yWxQrn5xjPlKrPFqOQkm3_kyDcJfgIFugmD_wuzN6k&usqp=CAU",
    name: "Health products",
    discription: "Health products ",
  },
  {
    id: 6,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT08rulMkvWxsr0vKbuCgGyFbIXetk9h3iVAkse6lmz-a_gbCoQlzLV5SVATZGgBqfZO50&usqp=CAU",
    name: "Fitness Products",
    discription: "All type of fitenss products",
  },
  // {
  //   id: 7,
  //   img: "https://i.pinimg.com/736x/53/06/f1/5306f17104d3206883a3fa37b5fb7139.jpg",
  //   name: "Appliances",
  //   discription: "All type of appliances",
  // },
  // {
  //   id: 8,
  //   img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzzbxSNpckYcYvUr7_PDbM1DJYZfIaoaQWRA&usqp=CAU",
  //   name: "Home appliances",
  //   discription: "All kind of sofa,dining, wardrobe etc home products",
  // },
  // {
  //   id: 9,
  //   img: "https://img3.exportersindia.com/product_images/bc-full/dir_178/5327018/grocery-products-1510312058-3444389.jpeg",
  //   name: "Grocery products",
  //   discription: "All type of grocery and food products",
  // },
  // {
  //   id: 10,
  //   img: "https://thumbs.dreamstime.com/b/cosmetic-woman-makeup-beauty-products-decorated-star-confetti-coral-table-top-view-flat-lay-cosmetic-woman-makeup-148122166.jpg",
  //   name: "Beauty products",
  //   discription: "All type of beauty products",
  // },
];

export const floatingProducts = [
  {
    id: 1,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVHnlbX64KPSB3FBHfSSg8YmSW-SbDP0-weA&usqp=CAU",
    title: "T-shirt",
  },
  {
    id: 2,
    img: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1610416577-vans-1610416571.jpg",
    title: "Shoe",
  },
  {
    id: 3,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW4Jrq8nnX8qr5QRUSkhYaP4_DCB-J27pkDg&usqp=CAU",
    title: "Pant",
  },
  {
    id: 3,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW4Jrq8nnX8qr5QRUSkhYaP4_DCB-J27pkDg&usqp=CAU",
    title: "Pant",
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/71gkRrWoOfL._SL1500_.jpg",
    title: "Pan",
  },
];

export const allProducts = [
  {
    // Kitchen Prodcuts
    category_id:1,
    id: 1,
    img: "https://images.unsplash.com/photo-1617784625140-515e220ba148?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Y3JvY2tlcnl8ZW58MHx8MHx8&ixlib=rb-1.2.1&w=1000&q=80",
    name: "Crockery set",
    discription: "A complete set of crockery in a single pack",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:1,
    id: 2,
    img: "https://cdn.shopify.com/s/files/1/2793/2598/products/jagdamba-cutlery-limited-cookware-kadhai-with-glass-lid-quantum-12818381111342_500x.jpg?v=1570071855",
    name: "Kadhai ",
    discription: "This kadhai by Shri and Sam is made from premium quality aluminium which is highly durable  ",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:1,
    id: 3,
    img: "https://www.bigbasket.com/media/uploads/p/l/40077281_3-nirlon-non-stick-concave-dosa-chapati-tawa-285-cm-red.jpg",
    name: "Non-Stick Concave Tawa",
    discription: "Nirlon presents this high-quality aluminium Non-stick tawa - a high-quality tawa which will add ease and comfort to your kitchen chores. ",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:1,
    id: 4,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSmkujUfo8-_OWpaDfFlKsnQkZh2P1mklLhPqJM7SmVRuA74StsM43byRavnheaqzWdtk&usqp=CAU",
    name: "Grill Pan",
    discription: "  Buy Lodge Color ECSGP43 Enameled Cast Iron Square Grill Pan, Island Spice Red, 10-inch Online at Low Prices in India",   
    totalStock: "10",
    price: "10",
  },
  {
    category_id:1,
    id: 5,
    img: "https://rukminim1.flixcart.com/image/612/612/kpft18w0/pot-pan/t/a/k/st-ci-021-70-s-kitchen-original-imag3z74r9m8ggdy.jpeg?q=70",
    name: "Aluminium, Non-stick",
    discription: "Peher Paniarakkal 0.5 L capacity 17 cm diameter  (Aluminium, Non-stick)",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:1,
    id: 6,
    img: "https://rukminim1.flixcart.com/image/416/416/kqgyhe80/pot-pan/n/b/e/sst15-hawkins-original-imag4h8bfmahpwn7.jpeg?q=70",
    name: "HAWKINS Tea Pan",
    discription: "The stainless steel Hawkins t pan is ideal for making tea – up to 6 cups at a time. It is also ideal for making coffee and soup, for boiling milk and water, for cooking instant noodles and for reheating food. ",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:1,
    id: 7,
    img: "https://rukminim1.flixcart.com/image/416/416/kjym9ow0/cookware-set/7/7/n/stainless-steel-sauce-pan-for-kitchen-restaurant-cooking-heat-original-imafzerx8wt4kj4a.jpeg?q=70",
    name: "Redific Saucepan",
    discription: "Redific Saucepan Set Sauce pan for Tea Pan saucepan combo steel saucepan sauce pan chai milk pan pot boiler container coffee maker",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:1,
    id: 8,
    img: "https://rukminim1.flixcart.com/image/416/416/k4u7i4w0/pot-pan/h/h/g/csi-001-crystal-original-imafnnysc5n2bpyk.jpeg?q=70",
    name: "TV",
    discription: "TV",
    totalStock: "10",
    price: "10",
  },
  {
    // Fashion prodcuts
   category_id:2,
    id: 1,
    img: "https://rukminim1.flixcart.com/image/487/584/km57hjk0/shirt/l/t/6/free-news-paper-enjoy-fashion-original-imagf4a3uzpf8ugm.jpeg?q=50",
    name: "Blend Printed Shirt",
    discription: "Cotton Polyester Blend Printed Shirt Fabric  (Unstitched)",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:2,
    id: 2,
    img: "https://rukminim1.flixcart.com/image/800/960/kc0u7bk0/shirt/k/a/a/m-pk19sh09g-surhi-original-imaft8vgvhmhbhsy.jpeg?q=50",
    name: "Men Slim Fit Checkered Casual Shirt",    
    discription: "This shirt by Shri and Sam is made from premium quality cotton which is highly durable  ",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:2,
    id: 3,
    img: "https://i.pinimg.com/originals/a5/93/d5/a593d556720a2a66e88f12c6225668bf.jpg",
    name: "VAN GOGH PAINTINGS GRID TEE",              
    discription: "VAN GOGH PAINTINGS GRID TEE - Cosmique Studio | Aesthetic Clothing #t-shirt #cute #t-shirt | Retro outfits, Aesthetic clothes, Vintage outfits ",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:2,
    id: 4,
    img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/affordableonline-1594998657.jpg?crop=0.502xw:1.00xh;0.251xw,0&resize=640:*",
    name: "Mens Black jacket",
    discription: "Fully hand sticked premium jacket for men",   
    totalStock: "10",
    price: "10",
  },
  {
    category_id:2,
    id: 5,
    img: "https://rukminim1.flixcart.com/image/800/960/k3dc7m80/sweatshirt/m/5/p/xl-ttss000360-tokyo-talkies-original-imafmgmxjbu8uqfc.jpeg?q=50",
    name: "Women Sweatshirt",
    discription: "Full Sleeve Printed Women Sweatshirt",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:2,
    id: 6,
    img: "https://rukminim1.flixcart.com/image/800/960/kjiwfbk0-0/t-shirt/e/k/s/m-t305-as10yldnwh-seven-rocks-original-imafz2qfvx7tznnn.jpeg?q=50",
    name: "Striped Men Round Neck Yellow T-Shirt",
    discription: "Striped Men Round Neck Yellow T-Shirt in many colors. ",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:2,
    id: 7,
    img: "https://rukminim1.flixcart.com/image/800/960/klgx0280/t-shirt/w/e/n/xxl-t51-seven-rocks-original-imagykzfbhzzrwby.jpeg?q=50",
    name: "T-shirt",
    discription: "Striped Men Polo Neck Light Blue, Blue T-Shirt",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:2,
    id: 8,
    img: "https://rukminim1.flixcart.com/image/800/960/kkec4280/t-shirt/g/q/o/xl-t345-blwhor-new-eyebogler-original-imafzr4y3ghsrgzh.jpeg?q=50",
    name: "Hoody",
    discription: "Color Block Men Hooded Neck Multicolor T-Shirt",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:2,
    id: 9,
    img: "https://rukminim1.flixcart.com/image/800/960/kt39jm80/sari/u/6/z/free-s185456-fabwomen-unstitched-original-imag6gjwmdzj4zg2.jpeg?q=50",
    name: "Silk Saree ",
    discription: "Printed Mysore Art Silk Saree  (Pink) ",
    totalStock: "10",
    price: "10",
  },
  {
    // Electronic items
   category_id:3,
    id: 1,
    img: "https://rukminim1.flixcart.com/image/416/416/kqv8vww0/trimmer/d/n/q/0-5-12-mm-v-183-original-professional-rechargeable-hair-clipper-original-imag4s55frhpkm8f.jpeg?q=70",
    name: "VGR V-183 Original Professional ",
    discription: "VGR V-183 Original Professional Rechargeable Hair Clipper Runtime: 120 min Trimmer for Men  (Black, Blue)",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:3,
    id: 2,
    img: "https://rukminim1.flixcart.com/image/416/416/ka8jdzk0/iron/z/z/g/orient-electric-fabri-press-fabri-press-difp10bp-original-imafru238gvzzhym.jpeg?q=70",
    name: "Orient Electric Fabri Press ",    
    discription: "Orient Electric Fabri Press DIFP10BP 1000 W Dry Iron  (Blue, Black)#JustHere",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:3,
    id: 3,
    img: "https://rukminim1.flixcart.com/image/416/416/kingqkw0-0/hair-straightener/s/v/x/hp8302-06-philips-original-imaf9jzzzurgqykt.jpeg?q=70",
    name: "PHILIPS HP8302/06 Hair Straightener  (Black)",              
    discription: "PHILIPS HP8302/06 Hair Straightener  (Black)",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:3,
    id: 4,
    img: "https://rukminim1.flixcart.com/image/416/416/ksoz53k0/electric-insect-killer/t/w/d/electric-led-bug-zapper-mosquito-killer-trap-lamp-home-indoor-original-imag677s8tg8nefm.jpeg?q=70",
    name: "Woomzy Electric LED Bug Zapper Mosquito Killer Trap Lamp",
    discription: "Woomzy Electric LED Bug Zapper Mosquito Killer Trap Lamp, Home, Indoor & Outdoor Insect Electric Killer Lamp (Cobra White Killer Lamp) Electric Insect Killer  (Lantern)",   
    totalStock: "10",
    price: "10",
  },
  {
    category_id:3,
    id: 5,
    img: "https://rukminim1.flixcart.com/image/416/416/km0x5zk0/tripod/tripod-kit/l/c/6/3110-mobile-phone-camera-stand-holder-tripod-kit-with-collar-original-imagfyqyhjqrwhra.jpeg?q=70",
    name: "Naeco 3110 Mobile Phone & Camera Stand Holder ",
    discription: "Naeco 3110 Mobile Phone & Camera Stand Holder Tripod Kit with Collar Microphone Kit with Voice Recording Filter Mic for Recording Singing YouTube (2in1 Combo Pack) Tripod, Monopod Kit, Tripod Kit, Monopod (Silver, Black, Supports Up to 3000 g) Tripod Kit  (Silver, Supports Up to 3000 g)",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:3,
    id: 6,
    img: "https://rukminim1.flixcart.com/image/416/416/jz8qf0w0/hair-dryer/d/a/8/bird-newnova-1000w-n-1290-original-imafj9w8zhma9gap.jpeg?q=70",
    name: "Hair Dryer ",
    discription: "Bird N-1290 Hair Dryer  (1000 W, Pink) ",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:3,
    id: 7,
    img: "https://rukminim1.flixcart.com/image/416/416/k0wqwsw0/electric-kettle/g/t/d/butterfly-rapid-kettle-1-5-litre-wave-750-ml-water-bottle-rapid-original-imafkfy7zaekbubs.jpeg?q=70",
    name: "Butterfly Rapid Kettle ",
    discription: "Butterfly Rapid Kettle 1.5 Litre + Eco 750 Ml Water Bottle",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:3,
    id: 8,
    img: "https://rukminim1.flixcart.com/image/416/416/kcw9w280/digital-thermometer/f/y/w/ozocheck-mt101p-digital-thermometer-fever-alarm-beeper-alert-ce-original-imaftx7fwxvhuysr.jpeg?q=70",
    name: "Ozocheck Digital thermometer ",
    discription: "Ozocheck Digital thermometer | Fever Alarm & Beeper Alert | CE Approved & 10 seconds Fast Reading for Kids & Adults MT101P Thermometer  (White)",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:3,
    id: 9,
    img: "https://rukminim1.flixcart.com/image/416/416/kppt47k0/immersion-rod/c/n/q/1500-submersible-nih-430-05-nova-original-imag3vuhz6z7g3bm.jpeg?q=70",
    name: "Immersion Heater Rod ",
    discription: "Nova Submersible NIH 430-05 1500 W Immersion Heater Rod  (Water) ",
    totalStock: "10",
    price: "10",
  },
  // Footware Products
  {
    category_id:4,
    id: 1,
    img: "https://rukminim1.flixcart.com/image/800/960/kl6wx3k0/shoe/b/9/c/7-springw-luxury-fashion-white-original-imagyd39gk8whjbv.jpeg?q=50",
    name: "Casual sneaker shoes ",
    discription: "Luxury Fashionable casual sneaker shoes and partywear shoes Casuals For Men  (White)",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:4,
    id: 2,
    img: "https://rukminim1.flixcart.com/image/800/960/kdoup3k0-0/sandal/q/j/i/black-001-xylus-black-original-imafujq9nbkabbch.jpeg?q=50",
    name: "Men Black Flats Sandal ",    
    discription: "Premium leather sandlas for men",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:4,
    id: 3,
    img: "https://rukminim1.flixcart.com/image/800/960/kg6vfrk0-0/slipper-flip-flop/p/3/4/10-mrj1507-aadi-orange-original-imafwhk4vavaxaty.jpeg?q=50",
    name: "Slides",              
    discription: "The best and comfortable slides multi colors",
    totalStock: "10",
    price: "10",
  },
  {
    category_id:4,
    id: 4,
    img: "https://rukminim1.flixcart.com/image/800/960/kb9ou4w0/shoe/o/4/0/shoes-for-men-black-36-badlav-black-original-imafghd4tsktkq7y.jpeg?q=50",
    name: "Mens Shoes",
    discription: "aadiOutdoors For Men  (Black)",   
    totalStock: "10",
    price: "10",
  },
  {
    category_id:4,
    id: 5,
    img: "https://rukminim1.flixcart.com/image/800/960/kl9rssw0/sandal/v/b/r/9-485-black-red-9-density-black-red-original-imagyfmhyujpjjyf.jpeg?q=50",
    name: "Men's sandals ",
    discription: "Men Red Sandal",
    totalStock: "10",
    price: "10",
  },
    // Health Products
    {
      categorry_id:5,
      id: 1,
      img: "https://rukminim1.flixcart.com/image/416/416/jzrb53k0/chyawanprash/h/h/q/2-chyawanprash-dabur-original-imafjpaudafxtyfz.jpeg?q=70",
      name: "Dabur Chyawanprash  (2 kg)",
      discription: "The Himalaya Drug Company Makali Campus, Tumkur main road,Bangalore- 562162",
      totalStock: "10",
      price: "10",
    },
    {
      categorry_id:5,
      id: 2,
      img: "https://rukminim1.flixcart.com/image/416/416/ktlu9ow0/antiseptic/g/q/k/antiseptic-disinfectant-liquid-for-first-aid-surface-cleaning-original-imag6wxqrfzsk5q6.jpeg?q=70",
      name: "Dettol Antiseptic Disinfectant liquid",    
      discription: "Dettol Antiseptic Disinfectant liquid for First aid, Surface Cleaning and Personal Hygiene, 550ml (Pack of 2) Antiseptic Liquid  (1100 ml, Pack of 2)",
      totalStock: "10",
      price: "10",
    },
    {
      categorry_id:5,
      id: 3,
      img: "https://rukminim1.flixcart.com/image/416/416/kafol8w0/vitamin-supplement/e/j/a/400-good-health-ayurvedic-medicine-pack-of-8-dr-biswas-original-imafrzr6zy3hchsw.jpeg?q=70",
      name: "Health Ayurvedic Medicine ",              
      discription: "Dr. Biswas Good Health Ayurvedic Medicine (Pack of 8)  (400)",
      totalStock: "10",
      price: "10",
    },
    {
      categorry_id:5,
      id: 4,
      img: "https://rukminim1.flixcart.com/image/416/416/krce64w0/mask-respirator/y/o/f/free-size-100-mask-100-00010-meltblown-surgical-mask-nea-original-imag55n4g74fqggv.jpeg?q=70",
      name: "Nea Pharmaceutical Mask with nose pin 3 layered ",
      discription: "Nea Pharmaceutical Mask with nose pin 3 layered / 3 ply with Meltblown layer in middle , Surgical Face mask 100% certified anti pollution - anti viral Mask with Nose-pin and soft Ear-loops Mask-100 - 00010 - Meltblown Water Resistant Surgical Mask With Melt Blown Fabric Layer  (Blue, Free Size, Pack of 100, 3 Ply)",   
      totalStock: "10",
      price: "10",
    },
    {
      categorry_id:5,
      id: 5,
      img: "https://rukminim1.flixcart.com/image/416/416/jlfh6kw0/body-pain-relief/r/w/m/120-joint-pain-relief-oil-120ml-ayurvedic-joint-pain-massage-oil-original-imaf6gz5kywvaxhz.jpeg?q=70",
      name: "Dr. Ortho Joint Pain Relief Oil  ",
      discription: "Dr. Ortho Joint Pain Relief Oil 120ml - Ayurvedic Joint Pain Massage Oil Liquid  (120 ml)",
      totalStock: "10",
      price: "10",
    },
     // Fitness Products
     {
      category_id:6,
      id: 1,
      img: "https://rukminim1.flixcart.com/image/416/416/jzrb53k0/chyawanprash/h/h/q/2-chyawanprash-dabur-original-imafjpaudafxtyfz.jpeg?q=70",
      name: "Home Gym Exercise",
      discription: "Deviant Buzz Plastic Orange Push Up Bar Stand For Home Gym Exercise(Quality Product) Push-up Bar",
      totalStock: "10",
      price: "10",
    },
    {
      category_id:6,
      id: 2,
      img: "https://rukminim1.flixcart.com/image/416/416/ks0onm80/treadmill/u/f/r/strong-surge-2-0-hp-peak-4-0-hp-motorized-foldable-treadmill-original-imag5zgnzph6xsqs.jpeg?q=70",
      name: "Auto-Incline Treadmill",    
      discription: "effingo Double Spring Waist Trimmer for Fat Burning & Weight loss Exercises(Multicolor) Ab Exerciser  (Multicolor)",
      totalStock: "10",
      price: "10",
    },
    {
      category_id:6,
      id: 3,
      img: "https://rukminim1.flixcart.com/image/416/416/kirr24w0-0/fitness-band/i/w/x/resistant-tube-toning-tube-resistant-band-full-body-fitness-original-imafyhpj8ejd8wfu.jpeg?q=70",
      name: "Shopeleven Resistant",              
      discription: "Shopeleven Resistant tube toning tube resistant band full body fitness exerciser rope Resistance Band  (Grey, Pack of 1)",
      totalStock: "10",
      price: "10",
    },
 
];


